---
deployment: cf

jobs:
  - name: micro
    templates:
      - postgres
  - name: micro_ng
    templates:
      - nats
      - nats_stream_forwarder
      - etcd
      - hm9000
      - cloud_controller_ng
      - cloud_controller_worker
      - cloud_controller_clock
      - uaa
      - haproxy
      - gorouter
      - dea_next
      - loggregator_trafficcontroller
      - doppler
      - metron_agent
      - dea_logging_agent
      - etcd_metrics_server
      - consul_agent

properties:
  networks:
    apps: default

  domain: 10.49.49.49.xip.io
  ssl:
    skip_cert_verify: true
  system_domain: 10.49.49.49.xip.io
  system_domain_organization: DevBox
  app_domains:
    - 10.49.49.49.xip.io

  disk_quota_enabled: true

  nats:
    user: nats
    password: c1oudc0w
    address: 10.49.49.49
    port: 4222
    machines:
      - 10.49.49.49

  dea_next:
    heartbeat_interval_in_seconds: 60

  cc: &cc
    bulk_api_password: c1oudc0w
    srv_api_uri: https://api.10.49.49.49.xip.io
    db_logging_level: debug2
    logging_level: debug2
    ccng.logging_level: debug2
    db_encryption_key: c1oudc0w
    quota_definitions:
      default:
        memory_limit: 10240
        total_services: 100
        non_basic_services_allowed: true
        total_routes: 1000
        trial_db_allowed: true
    hm9000_noop: false
    staging_upload_user: uploaduser
    staging_upload_password: c1oudc0w
    install_buildpacks:
      - name: java_buildpack
        package: buildpack_java
      - name: ruby_buildpack
        package: buildpack_ruby
      - name: nodejs_buildpack
        package: buildpack_nodejs
    security_group_definitions:
      - name: public_networks
        rules:
          - protocol: all
            destination: 0.0.0.0-9.255.255.255
          - protocol: all
            destination: 11.0.0.0-169.253.255.255
          - protocol: all
            destination: 169.255.0.0-172.15.255.255
          - protocol: all
            destination: 172.32.0.0-192.167.255.255
          - protocol: all
            destination: 192.169.0.0-255.255.255.255
      - name: private_networks
        rules:
          - protocol: all
            destination: 10.0.0.0-10.255.255.255
          - protocol: all
            destination: 172.16.0.0-172.31.255.255
          - protocol: all
            destination: 192.168.0.0-192.168.255.255
      - name: dns
        rules:
          - protocol: tcp
            destination: 0.0.0.0/0
            ports: '53'
          - protocol: udp
            destination: 0.0.0.0/0
            ports: '53'
    default_running_security_groups:
      - public_networks
      - private_networks
      - dns
    default_staging_security_groups:
      - public_networks
      - private_networks
      - dns
    internal_api_password: c1oudc0w
  ccng: *cc

  ccdb: &ccdb
    db_scheme: postgres
    address: 10.49.49.49
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: c1oudc0w
    databases:
      - tag: cc
        name: ccdb
        citext: true
  ccdb_ng: *ccdb

  uaadb:
    db_scheme: postgresql
    address: 10.49.49.49
    port: 5524
    roles:
      - tag: admin
        name: uaaadmin
        password: c1oudc0w
    databases:
      - tag: uaa
        name: uaadb
        citext: true

  databases:
    db_scheme: postgres
    address: 10.49.49.49
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: c1oudc0w
      - tag: admin
        name: uaaadmin
        password: c1oudc0w
    databases:
      - tag: cc
        name: ccdb
        citext: true
      - tag: uaa
        name: uaadb
        citext: true
  db: databases

  uaa:
    ldap:
      enabled: true
      profile_type: search-and-bind
      url: 'ldap://140.92.26.148:3890/'
      userDN: 'cn=admin,dc=puppetlabs,dc=test'
      userPassword: 'test'
      searchBase: 'dc=puppetlabs,dc=test'
      searchFilter: 'cn={0}'
    login:
      addnew: false
      client_secret: c1oudc0w
    url: https://uaa.10.49.49.49.xip.io
    catalina_opts: -Xmx384m -XX:MaxPermSize=128m
    jwt:
      signing_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIICXAIBAAKBgQDHFr+KICms+tuT1OXJwhCUmR2dKVy7psa8xzElSyzqx7oJyfJ1
        JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMXqHxf+ZH9BL1gk9Y6kCnbM5R6
        0gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBugspULZVNRxq7veq/fzwIDAQAB
        AoGBAJ8dRTQFhIllbHx4GLbpTQsWXJ6w4hZvskJKCLM/o8R4n+0W45pQ1xEiYKdA
        Z/DRcnjltylRImBD8XuLL8iYOQSZXNMb1h3g5/UGbUXLmCgQLOUUlnYt34QOQm+0
        KvUqfMSFBbKMsYBAoQmNdTHBaz3dZa8ON9hh/f5TT8u0OWNRAkEA5opzsIXv+52J
        duc1VGyX3SwlxiE2dStW8wZqGiuLH142n6MKnkLU4ctNLiclw6BZePXFZYIK+AkE
        xQ+k16je5QJBAN0TIKMPWIbbHVr5rkdUqOyezlFFWYOwnMmw/BKa1d3zp54VP/P8
        +5aQ2d4sMoKEOfdWH7UqMe3FszfYFvSu5KMCQFMYeFaaEEP7Jn8rGzfQ5HQd44ek
        lQJqmq6CE2BXbY/i34FuvPcKU70HEEygY6Y9d8J3o6zQ0K9SYNu+pcXt4lkCQA3h
        jJQQe5uEGJTExqed7jllQ0khFJzLMx0K6tj0NeeIzAaGCQz13oo2sCdeGRHO4aDh
        HH6Qlq/6UOV5wP8+GAcCQFgRCcB+hrje8hfEEefHcFpyKH+5g1Eu1k0mLrxK2zd+
        4SlotYRHgPCEubokb2S1zfZDWIXW3HmggnGgM949TlY=
        -----END RSA PRIVATE KEY-----
      verification_key: |
        -----BEGIN PUBLIC KEY-----
        MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDHFr+KICms+tuT1OXJwhCUmR2d
        KVy7psa8xzElSyzqx7oJyfJ1JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMX
        qHxf+ZH9BL1gk9Y6kCnbM5R60gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBug
        spULZVNRxq7veq/fzwIDAQAB
        -----END PUBLIC KEY-----
    cc:
      client_secret: c1oudc0w
    admin:
      client_secret: c1oudc0w
    batch:
      username: batch-username
      password: c1oudc0w
    clients:
      login:
        override: true
        scope: openid,oauth.approvals
        authorities: oauth.login,scim.write,clients.read,notifications.write,critical_notifications.write,emails.write,scim.userids,password.write
        secret: c1oudc0w
        authorized-grant-types: authorization_code,client_credentials,refresh_token
      notifications:
        secret: c1oudc0w
        authorities: cloud_controller.admin,scim.read
        authorized-grant-types: client_credentials
      doppler:
        override: true
        authorities: uaa.resource
        secret: c1oudc0w
      cloud_controller_username_lookup:
        authorities: scim.userids
        secret: c1oudc0w
        authorized-grant-types: client_credentials
      gorouter:
        authorities: clients.read,clients.write,clients.admin,route.admin,route.advertise
        authorized-grant-types: client_credentials,refresh_token
        scope: openid,cloud_controller_service_permissions.read
        secret: c1oudc0w

    scim:
      users:
      - admin|c1oudc0w|scim.write,scim.read,openid,cloud_controller.admin,doppler.firehose,uaa.admin,password.write

  etcd:
    machines:
      - 10.49.49.49

  etcd_metrics_server:
    nats:
      username: nats
      password: c1oudc0w
      machines:
        - 10.49.49.49

  consul:
      require_ssl: false
      encrypt_keys: []

  router:
    port: 8888
    enable_routing_api: false
    status:
      port: 18888
      user: gorouter
      password: c1oudc0w
    servers:
      z1:
        - 10.49.49.49
      z2: []

  login:
    enabled: false

  loggregator:
    incoming_port: 13456
    dropsonde_incoming_port: 13457
    outgoing_dropsonde_port: 18081
    doppler_port: 8081

  metron_agent:
    zone: default
    status:
      user: trafic_controller
      password: c1oudc0w
      port: 6799
    incoming_port: 3456
    dropsonde_incoming_port: 3457
    deployment: default

  doppler:
    zone: default
    status:
      user: loggregator
      password: c1oudc0w
      port: 5768
    incoming_port: 13456
    dropsonde_incoming_port: 13457
    outgoing_port: 8081
    servers:
      default:
        - 10.49.49.49

  traffic_controller:
    zone: default
    status:
      user: trafic_controller
      password: c1oudc0w
      port: 6789
    incoming_port: 23456
    outgoing_port: 18080

  metron_endpoint:
    shared_secret: c1oudc0w
    host: 127.0.0.1
    port: 3456
    dropsonde_port: 3457

  logger_endpoint:
   port: 4443

  loggregator_endpoint:
    shared_secret: c1oudc0w

  doppler_endpoint:
    shared_secret: c1oudc0w

  dropsonde:
    enabled: true

  ha_proxy:
    ssl_pem: |
      -----BEGIN CERTIFICATE-----
      MIIDKDCCAhACCQDelKRBKQT7JDANBgkqhkiG9w0BAQsFADBWMQswCQYDVQQGEwJV
      UzEUMBIGA1UECAwLQ29ubmVjdGljdXQxEjAQBgNVBAcMCU5ldyBIYXZlbjEdMBsG
      A1UEAwwUKi4xMC40OS40OS40OS54aXAuaW8wHhcNMTUxMDA3MDg1NTMxWhcNMTYx
      MDA2MDg1NTMxWjBWMQswCQYDVQQGEwJVUzEUMBIGA1UECAwLQ29ubmVjdGljdXQx
      EjAQBgNVBAcMCU5ldyBIYXZlbjEdMBsGA1UEAwwUKi4xMC40OS40OS40OS54aXAu
      aW8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC8hudHhscLyt2FG8bc
      6j+ck8b4CCZ5VSsLtnfK4rF66D+dWS3O/9RWCVNgjq43nQD4JAZMk2AaoqoPkj1u
      ne5K/9DmmCg4qXTd/sb7hJqkRlCbp7lD0WFYGNUBRdAeJUmB8hze+mieBThF+cs8
      4tE5S/g6qiI47M49VEzV+GfyyMsHqPIKkYc7jnNeabn/51bZV04Ie1VGxJd0QfA9
      Amj1i4FVb2L7caTIwwLBYIWYahDE/yU9a5tF6H07siEmYxPpAE2QDMVVxhghbzWc
      LUIfykZ/spUvpEogf72u3St4u4GQPVNxCp7Kk1hQ6KSNz3f3MLVGAJ5djCpvCnjC
      P1HDAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAJrvv7qBJDoQpwnO7Ygf32T+gNoK
      YHSnG7YJp/xuVonTSBnNcMtiop/5uedCzMQY2UbGobnOhjMd/U8JNPk6WdNEEHoH
      G9X6uC+AE0/NCVG5t+GIJSRFryO4j+JlUbiNVvZlC3dxgwxc5YjrajjWSqcJmMqP
      LULtAIdTS7cLMjXiOvAiX31QyX2mkLDQAgLxnoM8JpAUUonXvfE0BiVTsEbtTt0N
      Ttrho4+tP8ksyTwovoUF24ED1dsDQuZIEhcxX80kCWFTbmno7EbRZjxaT1yEedfn
      su0HJEfbjxc3mT59ewZb1/ksVbhbg1wxK+Joyan79QL9Mr9be9RbgMwdK9k=
      -----END CERTIFICATE-----
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAvIbnR4bHC8rdhRvG3Oo/nJPG+AgmeVUrC7Z3yuKxeug/nVkt
      zv/UVglTYI6uN50A+CQGTJNgGqKqD5I9bp3uSv/Q5pgoOKl03f7G+4SapEZQm6e5
      Q9FhWBjVAUXQHiVJgfIc3vpongU4RfnLPOLROUv4OqoiOOzOPVRM1fhn8sjLB6jy
      CpGHO45zXmm5/+dW2VdOCHtVRsSXdEHwPQJo9YuBVW9i+3GkyMMCwWCFmGoQxP8l
      PWubReh9O7IhJmMT6QBNkAzFVcYYIW81nC1CH8pGf7KVL6RKIH+9rt0reLuBkD1T
      cQqeypNYUOikjc939zC1RgCeXYwqbwp4wj9RwwIDAQABAoIBABCWNeb/HqgU8yRw
      6zAok+wsvEa6QNhP+/eN2EBLbZ4IrQAlBni93Wqsa1+FbiKKd7ldQgietsfhI+E2
      1pzS3FJQ64o+PNuvXQ7jCZK7efeWECWBvjUPSOc9WBBCmirs0OjT6mJb2bR9dRQD
      BDSZKBtIadCPg29KtmKC9jelIVAk37sa6a+7fEwnU2z2pg/pNdf+g166Y5RDoaid
      uXV2+/KBXlJRa8Ma3zeUukHlelmRC+N0CPHkjBUmnv1f1xKcJ08gmTPQizp2jzEZ
      3weot7RyVYSUW5g5On2u0VEBwKG5qVzUt1xvcX+5QyRf3gsIOflXk1VQV9ooepid
      PqivvMECgYEA4o26vfC/AR3X2tLfupfBIRJ8QNiN49EyvqJpCUucRrbo6p3pZps0
      mLRRsKlu4yvIcejzQV10ngzrMpQ4MNuXH/EAX5VGiXuJS/J0mF6ZBE85+I8dJ45A
      ly90PKMzdYgAc5LvrT3xZIFqbqXKglF+hnN2unZh4NYZxB5cFeob0xMCgYEA1Qfj
      KFnhnjInNVi+hQVDKygSZl9bARpScyMI2U3ntrwigfPT21IAvXmVjolChF1imWu4
      78bbpBWeAcCoW/tycyg4Y7SMNBUecc3J2/OfdULBDiS2c+i+xbnYIqmsTUXI28wy
      BmddKOst74uM2CO1Jl4YyMd3Fdv3YhfbyxgkrJECgYAoSjpGozTktvD3Wn8tSOWw
      wv/T7G83b7HNk0aIv6iYLtk3OEQU2k89RPwuJcOxpMyt7VatbjhaD0QYp6FilvrG
      VG7TkNGNi6m8Fu9DVbdyu8A8gv8VVMgJ2weZ7RAuu7QQ2bXEInr2e8l4ygU8rc+J
      i6k2uezoNks4xIlt4Ed4fwKBgDf77aeiD1fqqEEtxEvi+SbzTfqXXqwohbh6YY3y
      Gk38nTj3ohqGL2mb9UDTM6bjf9D/7UceRISXpcGiJtyddRNsY31YamwZjLmtsjna
      iXJgi6my3jwR02jVEUbyvjREfae9vvvN2D6zp4vHack3gRjHK85AFTyqZRXjXUC/
      ZIvxAoGBAMRJbY68g8z1AKzyLAbO457H0tUtGYdjFfSILHgglYLIE8Vmns7m95QF
      cRG1mXt2E+qWt6cu9hgOqgVs7YMHwB75bZT2rjD6ep5R7KOghNPqYCDQRIWTlDST
      bfwJTm0dIWx+T1zv7lTO+RKU77Dq4mwuSbFXCcV28QrY61GhFPcW
      -----END RSA PRIVATE KEY-----
