name: cf-mysql
director_uuid: db2e5009-4ea5-4893-8a2e-e7f618e7c54e

releases:
- name: cf-mysql
  version: 24

jobs:
- instances: 2
  name: mysql
  networks:
  - name: services1
    static_ips: 
    - 192.168.0.206
    - 192.168.0.207
  persistent_disk: 40960
  properties: 
    database_startup_timeout: 600
    admin_password: "123456" 
    cluster_ips:
    - 192.168.0.206
    - 192.168.0.207
    haproxy_ips: 
    - 192.168.0.208
    haproxy_mysql_user: haproxy_check
    max_connections: 1500
    network_name: services1
    seeded_databases: null
    syslog_aggregator: null
  release: cf-mysql
  resource_pool: services-small
  template: mysql
- instances: 1
  name: haproxy
  networks:
  - name: services1
    static_ips:
    - 192.168.0.208
    default: [dns, gateway]
  - name: floating
    static_ips:
    - 10.5.50.135
  properties:
    cluster_ips:
    - 192.168.0.206
    - 192.168.0.207
    external_domain: 140.92.25.12.xip.io
    haproxy_mysql_user: haproxy_check
    haproxy_stats_password: "123456"
    mysql_node:
      ip: 192.168.0.206
    nats:
      machines:
      - 140.92.25.12.xip.io
      password: "c1oudc0w"
      port: 4222
      user: nats
    network_name: services1
    syslog_aggregator: null
    proxy:
      api_username: admin
      api_password: admin
      proxy_ips:
      - 192.168.0.208
    external_host: p-mysql.140.92.25.12.xip.io
  release: cf-mysql
  resource_pool: services-small
  template: proxy
- instances: 1
  name: cf-mysql-broker
  networks:
  - name: services1
    static_ips:
    - 192.168.0.210
    default: [dns, gateway]
  - name: floating
    static_ips:
    - 10.5.50.137
  properties:
    auth_password: "123456"
    auth_username: "tester"
    cc_api_uri: "http://api.140.92.25.12.xip.io"
    cookie_secret: "123456"
    external_host: "p-mysql.140.92.25.12.xip.io"
    max_user_connections_default: 40
    mysql_node:
      admin_password: "123456"
      host: 10.5.50.135
      persistent_disk: 4096
    nats:
      machines:
      - 140.92.25.12
      password: "c1oudc0w"
      port: 4222
      user: nats
    network_name: services1
    networks:
      broker_network: services1
    services:
    - dashboard_client:
        id: p-mysql
        secret: "p-123456"
      description: A MySQL service for application development and testing
      id: 44b26033-1f54-4087-b7bc-da9652c2a539
      metadata:
        displayName: MySQL for Pivotal CF
        documentationUrl: http://docs.gopivotal.com/
        imageUrl: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAABoxJREFUeNrkW01sG0UUnkQ90FNNOfVHilvKBQS2iASHVtiCHkAqxI3ECZG4KOJGnOZQxCVxeuHnEJz0BlVjF3FCyg9UooeKOogeqBTkOEov/DlS056a2hfCASm8b3izXY/XZr07Xq/hSSs7jr2775v3vu+92Zm+vb098X+2fR2/wAeZCL0k6YjzEeHXA9pXa3SU+H2R35f++nCu0sn76+tEBJDTcDDNjsd8nm6LjmU68gRGKdQAkONwesKA063AyDEY1dAAwI5n6RgIKHVrDETOLxC+ACDHEeL5AB13AiJNICwHCgATG0Y8ExIyX2Egqh0HgAku38E89xMNKQKh2M6P+tt0PsUSFTbnBcvqTeYj8wDwiZcc9DtstkD3mjWaAuz8Qo8VeXOUDhO+AeCwX+rRSvccgZD3DAATXrEHwr6VnW0lk00BYKkrdVHjTapDvFlP0aoZygXhfOzQETH0zHMi+vhBecAqD3fExRvfyldD6pDnvsRdBHCFd9PE1SOP7Rexw0esv1d/+8V6f+XNt8TQ08+KlTsbYv3etijdvyu/j8+rf+6KJz+eMYn1eYqCnFsAKn5GHyM5dfo1kTh+QgxEDorvf//H6QH6HH/Dyve35evLn12SzupRsTZ+Qbzy+aU6wAykQlSvFvc5OO+5qcHowfHRwRdEYe22GL56Wayzo05R0cy5GgNi0HmVCjlu050jgImv4oX14dR3774nR/Odr770lb+Zk0kJEM7TATtmJ0S9Ekx5lbzFkTHK4W0Z0n7Jq/LwgUwfRYqGbaJVKZz1csbRwRdlfk9+s2imtSNSXNnckDyAcxu2NEd6PQBc9HjKfTD5xRvXG8jMj01eWxTDX1wWs2fOSlVAihnkgpRTBKS9nvENSNlm2fed6WEPEoQUxkkVwC8GQXAEIOXnjCZGHw6PUMjPnhm2gMB5wSuw2deHTQEwVAcAhX/Ua/hj1Mqa1GGk4AT0vF1DBTh/qygW3x6TkmoHAdcyxQlc7FkRkPQjWUVNrzFS4ycTYoFy15sK7Ijn5z+RUXCFz6HkFZxgKBXqAIh7LXowKhi1OgIjNUD1d86njqs6QIGAFEFhZSgKvAEQY0L69f1pOUKDNFJ6/quQdaoCvYIApZGzHD8UxfiphAkAonYAIq5D/lRSlKhxgeN+Kz7XkkgRheuqGgHRZ6BIGrAD4HqSExdeuVMOxHF7RM1QmilSRSokjj9lhgzb/QEI71Ni+Llbq7JkdWtod5tJJXhEOrq72zRt4LQCACW3F4VxUoK2AQDh1ehGkZOR/e7ZGDeMokYHAXKZJADwuWqXIasAuLD2Yz2IDM76vbtWSgQeAZKISKdxtGNg8nG6aV0x4tT1naey1976AtxpUpgMSanTfIHJkrs/qDwGe8MhnbzAJfFDRxuaIdQBCHUoTictMAAQvpgkQYWnA3CgSSpBZfC/DnSE1uUVAFtBgIAOT84dEAiqmkNEgFOac851qwYwbZgYUQBUgooE5DTIcy1zwZoU1cmunv1/tlTikRQ/IRXDwByhRYIAIBEEAKpKhOOxw0cdSa4hRbTaH2pR8l9lluwA4I9REaDJWR86/q3TdBppyCZI1SQARREim2IJxMhvVXfE1Z9u1/3/pWMn5IyzMQCw+oqqopoIwTNAtNeYVkchNE+jrKeHmn8wUAss64XQctBp4GTo9CB/hp8JNKiyekDSryMSBmvF8OgpQII+a4N8QyHEj5Br3XZeFksjY9JBXf6UiiA9pk6/6jv8nSrBfLcBQK+A/h8yia7zwfRHDaMNbkAh5QSQGwGyPxnSmyE8O+v60je7RMJJVI7V3T+szxAFPkgw17QXYGQKYZJEkOHktSU50arKZ/kkitrmrfYnZVb1ZXROzVA2DFxQFxGbZek85iHhPPL/a4oGD7NSWf2DZusD8MXpMIGg1hzIKbnNjbbnIxDZNPppVwAwCKiUwrgg0mvjE3VaSttqPiAdtlTwYalm64j7W/TKiICJ/4DzM63WD7tZKBkKafRaVznlvdsUUJEwETZpdFvvu4lgV3OCjGKhx5xPutk/4HpStIdAKLh13hUHOHACgAjrynEQXradH3jdMhPnjios64g97x3y9FyAJRIgzIUk5KNeN0753jbHy2vQRicCdnwVtX27e4SMA2ADIsnV42gvOG4cAC0iUgyGqV5CbZ/Nmd5L3NfJ3eMMRlI82jjtNk2g4+AZjHKxkxuo+7qxfV4tUXOwkqk9wW7tbwEGAJwbJQSR3aMDAAAAAElFTkSuQmCC
        longDescription: Provisioning a service instance creates a MySQL database.
          Binding applications to the instance creates unique credentials for each
          application to access the database.
        providerDisplayName: Pivotal Software
        supportUrl: http://gopivotal.com/support/
      name: p-mysql
      plans:
      - description: Shared MySQL Server
        id: ab08f1bc-e6fc-4b56-a767-ee0fea6e3f20
        max_storage_mb: 100
        max_user_connections: 20
        metadata:
          bullets:
          - Not for production use - server is not replicated
          - Shared MySQL server
          - 100 MB storage
          - 40 concurrent connections
          costs:
          - amount:
              usd: 0
            unit: MONTH
          displayName: 100 MB Dev
        name: 100mb-dev
      - description: Shared MySQL Server
        id: 11d0aa36-dcec-4021-85f5-ea4d9a5c8342
        max_storage_mb: 1000
        max_user_connections: 40
        metadata:
          bullets:
          - Not for production use - server is not replicated
          - Shared MySQL server
          - 1000 MB storage
          - 40 concurrent connections
          costs:
          - amount:
              usd: 0
            unit: MONTH
          displayName: 1 GB Dev
        name: 1gb-dev
      tags:
      - mysql
    skip_ssl_validation: true
    ssl_enabled: true
    syslog_aggregator: null
  release: cf-mysql
  resource_pool: services-small
  template: cf-mysql-broker

networks:
- name: services1
  subnets:
  - cloud_properties:
      net_id: 50e2b566-e5a6-4dcd-bf02-d7614dd76649
      subnet: 618f4fe0-b2ac-4bc9-b1c8-86fce5ea7dad
    dns:
    - 8.8.8.8
    gateway: 192.168.0.1
    range: 192.168.0.0/16
    reserved:
    - 192.168.0.2 - 192.168.0.200
    static:
    - 192.168.0.201 - 192.168.0.210
  type: manual
- name: floating
  type: vip
  cloud_properties: {}

properties: {}

resource_pools:
- cloud_properties:
    instance_type: m1.small
  name: services-small
  network: services1
  size: 5
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: 3100

update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_in_flight: 1
  update_watch_time: 30000-600000

compilation:
  cloud_properties:
    instance_type: m1.medium
  network: services1
  reuse_compilation_vms: true
  workers: 1

